"""The project manifest — a stable, human- and machine-readable record of what the
current ``vibedev-output/`` project *is*.

This is distinct from ``checkpoint.json`` (which is transient resume state, reset every
run and tombstoned on completion). The manifest is written once a run finishes and is the
source of truth that ``continue_development`` reads to learn the existing project before
extending it: the final ``ProjectSpec``, the original prompt, and the list of features
added so far. A companion ``PROJECT.md`` is generated for humans.
"""

import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel

from vibedev import config
from vibedev.models import ProjectSpec

MANIFEST_NAME = "project.json"
PROJECT_MD_NAME = "PROJECT.md"


class ProjectManifest(BaseModel):
    """What the current generated project is, and how it got here."""

    original_prompt: str
    project_name: str
    description: str
    spec: dict  # the final ProjectSpec, as model_dump()
    feature_history: list[str] = []  # feature prompts added via continue_development
    updated_at: str = ""


def manifest_path() -> Path:
    return config.OUTPUT_DIR / MANIFEST_NAME


def build_manifest(
    original_prompt: str, project: ProjectSpec, feature_history: list[str]
) -> ProjectManifest:
    spec = project.model_dump()
    # Per-file 'change' tags are build-time orchestration state, not part of the project's
    # identity — clear them so the stored manifest describes the project, not the last edit.
    for f in spec.get("files", []):
        f["change"] = None
    return ProjectManifest(
        original_prompt=original_prompt,
        project_name=project.project_name,
        description=project.description,
        spec=spec,
        feature_history=feature_history,
        updated_at=datetime.now(timezone.utc).isoformat(),
    )


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def save_manifest(manifest: ProjectManifest) -> None:
    """Persist the manifest (and refresh PROJECT.md) atomically."""
    _atomic_write(manifest_path(), manifest.model_dump_json(indent=2))
    _atomic_write(config.OUTPUT_DIR / PROJECT_MD_NAME, _render_project_md(manifest))


def load_manifest() -> ProjectManifest | None:
    """Read the manifest, or None if absent / unparseable."""
    path = manifest_path()
    if not path.exists():
        return None
    try:
        return ProjectManifest.model_validate_json(path.read_text(encoding="utf-8"))
    except (ValueError, OSError):
        return None


def _render_project_md(manifest: ProjectManifest) -> str:
    spec = ProjectSpec.model_validate(manifest.spec)
    lines = [
        f"# {spec.project_name}",
        "",
        spec.description,
        "",
        f'_Generated by vibedev from the prompt: "{manifest.original_prompt}"_',
        "",
        "## Files",
        "",
    ]
    for f in spec.files:
        comps = ", ".join(c.name for c in f.components) or "(none)"
        deps = ", ".join(f.depends_on) if f.depends_on else "none"
        lines.append(f"- `{f.path}` — {f.description}")
        lines.append(f"  - components: {comps}")
        lines.append(f"  - depends on: {deps}")
    if manifest.feature_history:
        lines += ["", "## Feature history", ""]
        lines += [f"{i}. {feat}" for i, feat in enumerate(manifest.feature_history, 1)]
    lines += ["", f"_Last updated: {manifest.updated_at}_", ""]
    return "\n".join(lines)
